version: "3.9"
services:
  db:
    image: postgres:15-alpine
    container_name: archangel_db
    environment:
      POSTGRES_USER: archangel
      POSTGRES_PASSWORD: archangel
      POSTGRES_DB: archangel
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U archangel -d archangel"]
      interval: 3s
      timeout: 3s
      retries: 20
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: {}