services:
  api:
    build: .
    env_file: .env
    environment:
      - PUBLIC_BASE_URL=${PUBLIC_BASE_URL}
      - SLACK_WEBHOOK_URL=${SLACK_WEBHOOK_URL}
    ports: ["8080:8080"]
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./:/app
    restart: unless-stopped
  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tasks
    ports: ["5432:5432"]
    volumes:
      - pg:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d tasks"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped
  nudge_worker:
    build: .
    command: sh -c "while true; do curl -s -X POST http://api:8080/nudges/stale/run >/dev/null 2>&1; sleep 3600; done"
    depends_on: [api]
volumes:
  pg: {}