defaults:
  aging_boost_per_day: 2
  stale_after_days: 3
  nudge_channel: "slack:#ops"

clients:
  acme:
    sla_hours: 48
    daily_cap_hours: 3
    importance_bias: 1.2
  meridian:
    sla_hours: 24
    daily_cap_hours: 2
    importance_bias: 1.5

task_types:
  bugfix:
    labels: ["bug", "fix"]
    checklist: ["Confirm repro", "Assess impact", "Patch", "Regression test", "Notify client"]
    subtasks:
      - title: "Draft fix plan"
      - title: "Implement"
      - title: "Review"
      - title: "Deliver"
      - title: "Follow up"
    default_effort_hours: 2
    importance: 4
  report:
    labels: ["report", "analysis"]
    checklist: ["Define question", "Pull data", "QA results", "Share link"]
    subtasks:
      - title: "Draft"
      - title: "Review"
      - title: "Deliver"
      - title: "Follow up"
    default_effort_hours: 3
    importance: 3
  onboarding:
    labels: ["setup"]
    checklist: ["Collect access", "Create project", "Baseline tasks"]
    subtasks:
      - title: "Prepare"
      - title: "Execute"
      - title: "Confirm access"
    default_effort_hours: 1.5
    importance: 3