name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint
        run: |
          ruff check .

      - name: Run unit tests (fast subset)
        run: |
          pytest -q tests/test_scoring_simple.py tests/test_scoring.py tests/test_retry.py tests/test_idempotency_util.py

      - name: Run integration tests against Supabase (if configured)
        if: ${{ secrets.SUPABASE_DATABASE_URL != '' }}
        env:
          DATABASE_URL: ${{ secrets.SUPABASE_DATABASE_URL }}
        run: |
          python -c "from app.db_pg import init; init(); print('Tables ready')"
          pytest -q -m integration

